/* Inspectable signal modules. Each returns standardized or bounded features; no UI code belongs here. */
window.BTCModules = (() => {
  const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)); const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
  const variance=a=>{if(a.length<2)return 0;const m=mean(a);return mean(a.map(x=>(x-m)**2));}; const sigmoid=x=>1/(1+Math.exp(-x));
  const z=(x,base,scale)=>clamp((x-base)/(scale||1),-3,3); const fmtPct=x=>`${x>=0?'+':''}${x.toFixed(2)}%`;

  // EWMA (RiskMetrics) captures recent volatility clustering without a fixed rolling window.
  function ewmaVolatility(returns, lambda=.94){let v=variance(returns.slice(-30))||1e-8;for(const r of returns.slice(-180))v=lambda*v+(1-lambda)*r*r;return Math.sqrt(v);}
  // GJR-GARCH(1,1) MLE-lite: coarse likelihood grid; negative shocks have their own gamma term.
  // Included because conditional variance clusters and asymmetric shock response can matter in crypto stress.
  function gjrGarch(returns){const r=returns.slice(-180);if(r.length<30)return {sigma:0,ratio:1,alpha:.07,beta:.88,gamma:.04};const long=variance(r)||1e-8;let best=null;for(const alpha of [.04,.07,.10])for(const beta of [.82,.88,.92])for(const gamma of [0,.03,.06]){if(alpha+beta+gamma/2>=.995)continue;let v=long,ll=0;for(const x of r){v=Math.max(1e-12,(1-alpha-beta-gamma/2)*long+alpha*x*x+beta*v+gamma*(x<0?x*x:0));ll+=Math.log(v)+x*x/v;}if(!best||ll<best.ll)best={ll,alpha,beta,gamma,v};}const last=r.at(-1),b=best;const next=Math.max(1e-12,(1-b.alpha-b.beta-b.gamma/2)*long+b.alpha*last*last+b.beta*b.v+b.gamma*(last<0?last*last:0));return {sigma:Math.sqrt(next),ratio:Math.sqrt(next/long),alpha:b.alpha,beta:b.beta,gamma:b.gamma};}
  function volatilityModule(closes){const rs=closes.slice(1).map((p,i)=>Math.log(p/closes[i]));const ewma=ewmaVolatility(rs),garch=gjrGarch(rs),baseline=Math.sqrt(variance(rs.slice(-120)))||1e-6;return {ewma,garch,volFeature:z(garch.sigma/baseline,1,.45),returns:rs};}

  // 1D Kalman local-level filter: denoises log-price and exposes adaptive local velocity.
  function kalmanTrend(closes){if(closes.length<3)return {level:0,velocity:0,distance:0,path:[]};let level=Math.log(closes[0]),P=1,q=2e-7,r=8e-7;const path=[];for(const price of closes){const obs=Math.log(price);P+=q;const k=P/(P+r);level=level+k*(obs-level);P=(1-k)*P;path.push(level);}const recent=path.slice(-8);const velocity=(path.at(-1)-recent[0])/Math.max(1,recent.length-1);return {level,velocity,distance:Math.log(closes.at(-1))-level,path,trendFeature:z(velocity,0,.00035)};}
  // Variance-ratio Hurst approximation: detects persistence vs mean reversion for regime weighting.
  function hurstRegime(returns){const x=returns.slice(-80);if(x.length<20)return {hurst:.5,regime:'Undetermined',persistence:0};const v1=variance(x);const q=5,diffs=[];for(let i=q;i<x.length;i++)diffs.push(x.slice(i-q,i).reduce((s,a)=>s+a,0));const vr=variance(diffs)/(q*v1||1);const h=clamp(.5+.5*Math.log(Math.max(vr,.05))/Math.log(q),.15,.85);return {hurst:h,regime:h>.54?'Persistent':h<.46?'Mean-reverting':'Mixed',persistence:clamp((h-.5)/.15,-1,1)};}
  function trendStateModule(closes){const v=volatilityModule(closes);const k=kalmanTrend(closes);const h=hurstRegime(v.returns);return {...k,...h,reversalFeature:z(-k.distance,0,.0012),trendFeature:k.trendFeature*(h.hurst>.5?1:0.35)};}

  // L2 book + classified prints: top depth, trade-flow imbalance, effective-spread proxy, VPIN-style volume buckets.
  // These proxies are included because microstructure is most relevant at the shortest horizon.
  function microstructureModule(book,trades,lastPrice){const bids=[...book.bids.entries()].sort((a,b)=>b[0]-a[0]).slice(0,12),asks=[...book.asks.entries()].sort((a,b)=>a[0]-b[0]).slice(0,12);const bid= bids.reduce((s,[,q])=>s+q,0),ask=asks.reduce((s,[,q])=>s+q,0),imb=(bid-ask)/(bid+ask||1);const bb=bids[0]?.[0],ba=asks[0]?.[0],mid=bb&&ba?(bb+ba)/2:lastPrice;const spread=bb&&ba?(ba-bb)/mid:0;const recent=trades.filter(t=>t.time>Date.now()-60e3);let buy=0,sell=0,effect=0;for(const t of recent){if(t.side==='buy')buy+=t.size;else if(t.side==='sell')sell+=t.size;if(mid)effect+=Math.abs(t.price-mid)/mid;}const flow=(buy-sell)/(buy+sell||1);const eff=recent.length?2*effect/recent.length:spread;const buckets=[];let cum=0,sgn=0,volTarget=Math.max(0.08,(buy+sell)/8);for(const t of trades.slice(-400)){cum+=t.size;sgn+=(t.side==='buy'?1:t.side==='sell'?-1:0)*t.size;if(cum>=volTarget){buckets.push(Math.abs(sgn)/cum);cum=0;sgn=0;}}const vpin=mean(buckets.slice(-12));return {imbalance:imb,flow,spread,effectiveSpread:eff,vpin,bookFeature:z(imb,0,.28),flowFeature:z(flow,0,.35),toxicityFeature:z(vpin,.5,.2)};}

  // Slow contextual sources: modifiers only. Missing/restricted sources become neutral.
  function contextModule(context){const fear=Number(context.fear?.value);const fearReversal=Number.isFinite(fear)?z(50-fear,0,28):0;const funding=Number(context.funding?.fundingRate);const fundingCrowding=Number.isFinite(funding)?z(-funding,0,.00035):0;const fee=Number(context.fees?.fastestFee);return {fear: Number.isFinite(fear)?fear:null,fearFeature:fearReversal,funding:Number.isFinite(funding)?funding:null,fundingFeature:fundingCrowding,fee:Number.isFinite(fee)?fee:null,chainFeature:Number.isFinite(fee)?z(fee,18,25):0};}

  // Transparent horizon-specific logistic ensemble. Online SGD updates only this session's mutable weights.
  const initialWeights={1:{b:0,book:1.05,flow:1.05,tox:.25,trend:.35,reversal:.15,vol:-.25,fear:.04,funding:.10,chain:0},5:{b:0,book:.55,flow:.65,tox:.2,trend:.85,reversal:.28,vol:-.32,fear:.07,funding:.16,chain:.02},15:{b:0,book:.2,flow:.3,tox:.12,trend:1.05,reversal:.42,vol:-.38,fear:.16,funding:.25,chain:.04},60:{b:0,book:.05,flow:.1,tox:.05,trend:1.15,reversal:.5,vol:-.45,fear:.25,funding:.35,chain:.06}};
  const weights=JSON.parse(JSON.stringify(initialWeights));
  function ensemble(features,horizon){const w=weights[horizon], x={book:features.micro.bookFeature,flow:features.micro.flowFeature,tox:features.micro.toxicityFeature,trend:features.trend.trendFeature,reversal:features.trend.reversalFeature,vol:features.vol.volFeature,fear:features.context.fearFeature,funding:features.context.fundingFeature,chain:features.context.chainFeature};let score=w.b;for(const k of Object.keys(x))score+=w[k]*x[k];return {p:clamp(sigmoid(score),.15,.85),score,x,weights:w};}
  function onlineUpdate(horizon,p,outcome,features){const w=weights[horizon];const e=clamp(outcome-p,-1,1),lr=.006;const x={book:features.micro.bookFeature,flow:features.micro.flowFeature,tox:features.micro.toxicityFeature,trend:features.trend.trendFeature,reversal:features.trend.reversalFeature,vol:features.vol.volFeature,fear:features.context.fearFeature,funding:features.context.fundingFeature,chain:features.context.chainFeature};w.b=clamp(w.b+lr*e,-1,1);for(const k in x)w[k]=clamp(w[k]+lr*e*x[k],-2,2);}
  // Wilson-style probability interval; effective n contracts as GARCH conditional volatility rises.
  function confidenceInterval(p,n,volRatio){const neff=Math.max(4,Math.min(120,n/(1+.9*Math.max(0,volRatio-1))));const zc=1.96,den=1+zc*zc/neff,center=(p+zc*zc/(2*neff))/den,half=zc*Math.sqrt(p*(1-p)/neff+zc*zc/(4*neff*neff))/den;return [clamp(center-half,.02,.98),clamp(center+half,.02,.98)];}
  return {volatilityModule,trendStateModule,microstructureModule,contextModule,ensemble,onlineUpdate,confidenceInterval,fmtPct,clamp};
})();