/**
 * BTC Signal Notebook v1.4
 * Persistent BTC-USD inference, honest prequential auditing, and bounded online learning.
 *
 * Data: public Coinbase ticker + 1-minute candles. This is research software, not trading advice.
 */
const MODEL_VERSION='v1.4';
const HORIZONS=[1,5,15,60];
const CANDLES_URL='https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=60';
const TICKER_URL='https://api.exchange.coinbase.com/products/BTC-USD/ticker';
const FEATURE_NAMES=['bias','m1','m5','trend','reversal','vol'];
const INITIAL={
  1:[0,.85,.20,.30,.12,-.28],
  5:[0,.45,.55,.78,.25,-.32],
  15:[0,.15,.50,1.00,.38,-.38],
  60:[0,.05,.25,1.12,.48,-.45]
};
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':'*','access-control-allow-methods':'GET, OPTIONS','cache-control':'no-store'}});
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const variance=a=>{if(a.length<2)return 0;const m=mean(a);return mean(a.map(x=>(x-m)**2));};
const sigmoid=x=>1/(1+Math.exp(-clamp(x,-30,30)));
const z=(x,c,s)=>clamp((x-c)/(s||1),-3,3);
const nowMinute=()=>Math.floor(Date.now()/60000)*60000;

// RiskMetrics EWMA: recent shocks receive more weight, capturing volatility clustering.
function ewma(returns,lambda=.94){let v=variance(returns.slice(-30))||1e-8;for(const r of returns.slice(-180))v=lambda*v+(1-lambda)*r*r;return Math.sqrt(v);}
// Lightweight GARCH(1,1): conditional variance feature and interval scale, safe for a scheduled Worker.
function garchLite(returns){const r=returns.slice(-180),long=variance(r)||1e-8,last=r.at(-1)||0,prior=r.at(-2)||0;const alpha=.08,beta=.89;const priorV=Math.max(1e-12,(1-alpha-beta)*long+alpha*prior*prior+beta*long);const next=Math.max(1e-12,(1-alpha-beta)*long+alpha*last*last+beta*priorV);return {sigma:Math.sqrt(next),ratio:Math.sqrt(next/long)};}
// One-dimensional Kalman local-level filter: adaptive denoised local trend.
function kalman(closes){let level=Math.log(closes[0]),P=1,q=2e-7,r=8e-7;const path=[];for(const price of closes){const obs=Math.log(price);P+=q;const k=P/(P+r);level+=k*(obs-level);P*=1-k;path.push(level);}const recent=path.slice(-8);return {level,velocity:(path.at(-1)-recent[0])/Math.max(1,recent.length-1),distance:Math.log(closes.at(-1))-level};}
// Variance-ratio Hurst approximation: reduces momentum influence during mean-reverting conditions.
function hurst(returns){const x=returns.slice(-80);if(x.length<20)return .5;const v=variance(x),q=5,d=[];for(let i=q;i<x.length;i++)d.push(x.slice(i-q,i).reduce((s,n)=>s+n,0));return clamp(.5+.5*Math.log(Math.max(variance(d)/(q*v||1),.05))/Math.log(q),.15,.85);}
function featureVector(candles,spot){const closes=candles.map(c=>c.close);closes[closes.length-1]=spot;const rs=closes.slice(1).map((p,i)=>Math.log(p/closes[i]));const g=garchLite(rs),k=kalman(closes),h=hurst(rs);const m1=((closes.at(-1)/closes.at(-2))-1)*100,m5=((closes.at(-1)/closes.at(-6))-1)*100;return {x:[1,z(m1,0,.12),z(m5,0,.25),z(k.velocity,0,.00035)*(h>.5?1:.35),z(-k.distance,0,.0012),z(g.ratio,1,.45)],garch:g,hurst:h,momentum1:m1,momentum5:m5};}
function dot(a,b){return a.reduce((s,x,i)=>s+x*b[i],0);}
function rawProbability(weights,x){return clamp(sigmoid(dot(weights,x)),.08,.92);}
// Beta-binomial empirical-Bayes calibration: small buckets shrink toward 50%, avoiding unstable claims.
function calibratedProbability(raw,cal){const bucket=Math.min(9,Math.floor(raw*10));const c=cal?.[bucket]||{up:0,n:0};const prior=10;return clamp((c.up+prior*.5)/(c.n+prior),.08,.92);}
function normalCdf(x){const t=1/(1+.2316419*Math.abs(x)),d=.3989423*Math.exp(-x*x/2),p=d*t*(.3193815+t*(-.3565638+t*(1.781478+t*(-1.821256+t*1.330274))));return x>=0?1-p:p;}
function confidence(p,sigma,minutes,n){const scale=Math.sqrt(Math.max(1,minutes))*Math.max(sigma,.0001);const samplePenalty=Math.min(.13,1/Math.sqrt(Math.max(20,n||0)));const half=clamp(.035+scale*95+samplePenalty,.05,.30);return [clamp(p-half,.02,.98),clamp(p+half,.02,.98)];}
function priceLine(p,spot,sigma,minutes,line){const direction=(p-.5)*2,scale=Math.max(sigma,.0001)*Math.sqrt(minutes),drift=direction*scale*.42;const over=clamp(1-normalCdf((Math.log(line)-Math.log(spot)-drift)/scale),.02,.98);return {over,under:1-over,low:Math.exp(Math.log(spot)+drift-1.28*scale),high:Math.exp(Math.log(spot)+drift+1.28*scale)};}

async function market(){const bust=`t=${Date.now()}`;const [cr,tr]=await Promise.all([fetch(`${CANDLES_URL}&${bust}`,{headers:{accept:'application/json'}}),fetch(`${TICKER_URL}?${bust}`,{headers:{accept:'application/json'}})]);if(!cr.ok)throw Error(`candles ${cr.status}`);if(!tr.ok)throw Error(`ticker ${tr.status}`);const rows=await cr.json(),tick=await tr.json(),spot=Number(tick.price);if(!Number.isFinite(spot)||spot<=0)throw Error('invalid ticker price');const candles=rows.map(x=>({time:+x[0]*1000,close:+x[4]})).filter(x=>Number.isFinite(x.close)).sort((a,b)=>a.time-b.time);if(candles.length<90)throw Error('insufficient candles');return {candles,spot};}
async function stateFor(env,h){const row=await env.DB.prepare('SELECT weights_json, calibration_json, trained_n FROM model_state WHERE model_version=? AND horizon_minutes=?').bind(MODEL_VERSION,h).first();if(!row)return {weights:[...INITIAL[h]],calibration:Array.from({length:10},()=>({up:0,n:0})),trained_n:0};try{return {weights:JSON.parse(row.weights_json),calibration:JSON.parse(row.calibration_json),trained_n:Number(row.trained_n)||0};}catch{return {weights:[...INITIAL[h]],calibration:Array.from({length:10},()=>({up:0,n:0})),trained_n:0};}}
function onlineLearn(s,x,y,raw,h){const lr=.006/Math.sqrt(1+s.trained_n/250);const err=y-raw;const ridge=.0008;for(let i=0;i<s.weights.length;i++)s.weights[i]=clamp(s.weights[i]+lr*(err*x[i]-ridge*(s.weights[i]-INITIAL[h][i])),-2.5,2.5);const b=Math.min(9,Math.floor(raw*10));s.calibration[b].n+=1;s.calibration[b].up+=y;s.trained_n+=1;}
async function ensureSchema(env){await env.DB.batch([
 env.DB.prepare('CREATE TABLE IF NOT EXISTS model_state (model_version TEXT NOT NULL, horizon_minutes INTEGER NOT NULL, weights_json TEXT NOT NULL, calibration_json TEXT NOT NULL, trained_n INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL, PRIMARY KEY(model_version,horizon_minutes))'),
 env.DB.prepare('CREATE INDEX IF NOT EXISTS resolved_by_horizon ON forecasts(model_version,horizon_minutes,resolved_at)')
]);}
async function audit(env){const now=nowMinute();try{const {candles,spot}=await market(),f=featureVector(candles,spot);const due=await env.DB.prepare('SELECT id,horizon_minutes,probability_up,feature_json,entry_price FROM forecasts WHERE model_version=? AND resolved_at IS NULL AND due_at<=? ORDER BY due_at ASC LIMIT 32').bind(MODEL_VERSION,now).all();const states={};for(const row of due.results||[]){const h=row.horizon_minutes;states[h]??=await stateFor(env,h);const moveBp=(spot-row.entry_price)/row.entry_price*10000;const flat=Math.abs(moveBp)<1.0; // 1 bp neutral zone; flat outcomes are never silently counted as down.
 if(!flat){let x;try{x=JSON.parse(row.feature_json).x;}catch{x=null;}if(Array.isArray(x)&&x.length===FEATURE_NAMES.length)onlineLearn(states[h],x,row.outcome_up??(spot>row.entry_price?1:0),row.probability_up,h);}
}
const stmts=[];for(const row of due.results||[]){const moveBp=(spot-row.entry_price)/row.entry_price*10000,flat=Math.abs(moveBp)<1.0;stmts.push(env.DB.prepare('UPDATE forecasts SET resolved_at=?, exit_price=?, outcome_up=? WHERE id=?').bind(now,spot,flat?null:(spot>row.entry_price?1:0),row.id));}
for(const h of HORIZONS){const s=states[h]||await stateFor(env,h);stmts.push(env.DB.prepare('INSERT OR REPLACE INTO model_state (model_version,horizon_minutes,weights_json,calibration_json,trained_n,updated_at) VALUES (?,?,?,?,?,?)').bind(MODEL_VERSION,h,JSON.stringify(s.weights),JSON.stringify(s.calibration),s.trained_n,now));const raw=rawProbability(s.weights,f.x),p=calibratedProbability(raw,s.calibration);stmts.push(env.DB.prepare('INSERT OR IGNORE INTO forecasts (model_version,created_at,due_at,horizon_minutes,entry_price,probability_up,feature_json) VALUES (?,?,?,?,?,?,?)').bind(MODEL_VERSION,now,now+h*60000,h,spot,p,JSON.stringify({x:f.x,raw,model_n:s.trained_n})));}
stmts.push(env.DB.prepare('INSERT OR REPLACE INTO audit_runs (run_at,price,status,detail) VALUES (?,?,?,?)').bind(now,spot,'ok',`resolved=${(due.results||[]).length}; candles=${candles.length}`));await env.DB.batch(stmts);return {ok:true,spot,now};
}catch(err){try{await env.DB.prepare('INSERT OR REPLACE INTO audit_runs (run_at,status,detail) VALUES (?,?,?)').bind(now,'error',String(err).slice(0,300)).run();}catch{}return {ok:false,error:String(err)};}}
function metrics(rows){const directional=rows.filter(r=>r.outcome_up===0||r.outcome_up===1),flats=rows.filter(r=>r.outcome_up===null);const n=directional.length,brier=n?mean(directional.map(r=>(r.probability_up-r.outcome_up)**2)):null,hit=n?mean(directional.map(r=>((r.probability_up>=.5)===(r.outcome_up===1)?1:0))):null;const bins=Array.from({length:5},(_,i)=>{const a=i*.2,b=a+.2,q=directional.filter(r=>r.probability_up>=a&&(i===4?r.probability_up<=b:r.probability_up<b));return {label:`${i*20}–${(i+1)*20}%`,n:q.length,forecast:q.length?mean(q.map(r=>r.probability_up)):null,observed:q.length?mean(q.map(r=>r.outcome_up)):null};});return {resolved:n,flat:flats.length,brier,hit,bins};}
async function auditApi(env,url){const per=Math.min(3000,Math.max(100,Number(url.searchParams.get('perHorizon')||720)));const all={};for(const h of HORIZONS){const r=await env.DB.prepare('SELECT probability_up,outcome_up,entry_price,exit_price,created_at,resolved_at FROM forecasts WHERE model_version=? AND horizon_minutes=? AND resolved_at IS NOT NULL ORDER BY resolved_at DESC LIMIT ?').bind(MODEL_VERSION,h,per).all();all[h]=metrics(r.results||[]);}const latest=await env.DB.prepare('SELECT * FROM audit_runs ORDER BY run_at DESC LIMIT 1').first();return json({modelVersion:MODEL_VERSION,generatedAt:Date.now(),window:{perHorizon:per,rule:'most recent resolved forecasts per horizon'},latestRun:latest||null,horizons:all});}
async function liveApi(env,url){try{const {candles,spot}=await market(),f=featureVector(candles,spot),minutes=clamp(Number(url.searchParams.get('minutes')||0),0,240),lineRaw=url.searchParams.get('line'),line=lineRaw===null?null:Number(lineRaw);if(line!==null&&(!Number.isFinite(line)||line<=0))return json({error:'line must be a positive USD value'},400);const projections={};for(const h of HORIZONS){const s=await stateFor(env,h),raw=rawProbability(s.weights,f.x),p=calibratedProbability(raw,s.calibration),ci=confidence(p,f.garch.sigma,h,s.trained_n);projections[h]={minutes:h,probabilityUp:p,rawProbability:raw,intervalLow:ci[0],intervalHigh:ci[1],trainingObservations:s.trained_n,referencePrice:spot,range:priceLine(p,spot,f.garch.sigma,h,spot)};}let custom=null;if(minutes){const near=HORIZONS.reduce((a,b)=>Math.abs(b-minutes)<Math.abs(a-minutes)?b:a),s=await stateFor(env,near),raw=rawProbability(s.weights,f.x),p=calibratedProbability(raw,s.calibration),ci=confidence(p,f.garch.sigma,minutes,s.trained_n),r=line===null?null:priceLine(p,spot,f.garch.sigma,minutes,line);custom={minutes,nearestHorizon:near,line,probabilityOver:r?.over??null,probabilityUnder:r?.under??null,referencePrice:spot,rangeLow:r?.low??null,rangeHigh:r?.high??null,probabilityUp:p,intervalLow:ci[0],intervalHigh:ci[1]};}return json({modelVersion:MODEL_VERSION,generatedAt:Date.now(),spot,features:{garchRatio:f.garch.ratio,hurst:f.hurst,momentum1:f.momentum1,momentum5:f.momentum5},projections,custom});}catch(err){return json({error:String(err)},502);}}
export default {async scheduled(controller,env,ctx){ctx.waitUntil(audit(env));},async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET, OPTIONS'}});if(url.pathname==='/api/live')return liveApi(env,url);if(url.pathname==='/api/audit')return auditApi(env,url);if(url.pathname==='/api/run')return json(await audit(env));return new Response('BTC Signal Notebook v1.4 — /api/live and /api/audit',{headers:{'content-type':'text/plain'}});}};
